# Generated by Django 4.1.5 on 2023-04-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='s',
            name='dt',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
